### PR TITLE
Termination criteria

### PR DESCRIPTION
**Pull request by agnusmaximus**
Here are some benchmark results on stripe 82

single inference
```c++
│ Row │ field        │ primary   │ celeste   │ diff       │ diff_sd   │ N   │
├─────┼──────────────┼───────────┼───────────┼────────────┼───────────┼─────┤
│ 1   │ position     │ 0.325255  │ 0.238023  │ 0.0872314  │ 0.0499956 │ 423 │
│ 2   │ missed_stars │ 0.0236407 │ 0.0851064 │ -0.0614657 │ 0.0124957 │ 423 │
│ 3   │ missed_gals  │ 0.0543735 │ 0.0189125 │ 0.035461   │ 0.0105737 │ 423 │
│ 4   │ mag_r        │ 0.199846  │ 0.359353  │ -0.159506  │ 0.0210032 │ 422 │
│ 5   │ color_ug     │ 1.27414   │ 0.705869  │ 0.568269   │ 0.0572582 │ 376 │
│ 6   │ color_gr     │ 0.325773  │ 0.210347  │ 0.115427   │ 0.0169646 │ 419 │
│ 7   │ color_ri     │ 0.202225  │ 0.166646  │ 0.0355791  │ 0.0156357 │ 422 │
│ 8   │ color_iz     │ 0.307054  │ 0.156048  │ 0.151006   │ 0.0202112 │ 422 │
│ 9   │ gal_fracdev  │ 0.261586  │ 0.316576  │ -0.0549897 │ 0.0236274 │ 177 │
│ 10  │ gal_ab       │ 0.192684  │ 0.124943  │ 0.0677414  │ 0.0102626 │ 177 │
│ 11  │ gal_scale    │ 1.68904   │ 1.77017   │ -0.0811269 │ 0.619594  │ 177 │
│ 12  │ gal_angle    │ 17.8127   │ 12.8645   │ 4.94818    │ 1.74678   │ 81  │
```
130.499247 seconds (8 threads)

joint infer @ 1 (585/585 sources converged)

```c++
│ Row │ field        │ primary   │ celeste   │ diff       │ diff_sd   │ N   │
├─────┼──────────────┼───────────┼───────────┼────────────┼───────────┼─────┤
│ 1   │ position     │ 0.461921  │ 0.241025  │ 0.220896   │ 0.107057  │ 425 │
│ 2   │ missed_stars │ 0.0258824 │ 0.103529  │ -0.0776471 │ 0.0136913 │ 425 │
│ 3   │ missed_gals  │ 0.0541176 │ 0.0164706 │ 0.0376471  │ 0.0107595 │ 425 │
│ 4   │ mag_r        │ 0.221218  │ 0.357399  │ -0.136181  │ 0.023306  │ 424 │
│ 5   │ color_ug     │ 1.27552   │ 0.701567  │ 0.573957   │ 0.0571882 │ 377 │
│ 6   │ color_gr     │ 0.326605  │ 0.209495  │ 0.117109   │ 0.0166096 │ 421 │
│ 7   │ color_ri     │ 0.202844  │ 0.165295  │ 0.0375493  │ 0.0154332 │ 424 │
│ 8   │ color_iz     │ 0.311025  │ 0.153971  │ 0.157054   │ 0.0191256 │ 424 │
│ 9   │ gal_fracdev  │ 0.265734  │ 0.31627   │ -0.0505355 │ 0.023274  │ 178 │
│ 10  │ gal_ab       │ 0.193415  │ 0.136412  │ 0.0570025  │ 0.0110832 │ 178 │
│ 11  │ gal_scale    │ 1.74291   │ 1.79126   │ -0.0483564 │ 0.610063  │ 178 │
│ 12  │ gal_angle    │ 17.8127   │ 14.1866   │ 3.62609    │ 1.78741   │ 81  │
```
- 302 seconds (8 threads)

joint infer @ .95 (558/585 sources converged)
```c++
│ Row │ field        │ primary   │ celeste   │ diff       │ diff_sd   │ N   │
├─────┼──────────────┼───────────┼───────────┼────────────┼───────────┼─────┤
│ 1   │ position     │ 0.356997  │ 0.23773   │ 0.119267   │ 0.0780409 │ 423 │
│ 2   │ missed_stars │ 0.0260047 │ 0.104019  │ -0.0780142 │ 0.013753  │ 423 │
│ 3   │ missed_gals  │ 0.0543735 │ 0.0165485 │ 0.0378251  │ 0.010809  │ 423 │
│ 4   │ mag_r        │ 0.20834   │ 0.356602  │ -0.148262  │ 0.0197846 │ 422 │
│ 5   │ color_ug     │ 1.2566    │ 0.686033  │ 0.570571   │ 0.057121  │ 376 │
│ 6   │ color_gr     │ 0.32552   │ 0.20382   │ 0.1217     │ 0.0163246 │ 419 │
│ 7   │ color_ri     │ 0.198864  │ 0.16176   │ 0.0371035  │ 0.0154959 │ 422 │
│ 8   │ color_iz     │ 0.291458  │ 0.133137  │ 0.158321   │ 0.0192617 │ 422 │
│ 9   │ gal_fracdev  │ 0.262856  │ 0.305289  │ -0.0424325 │ 0.0232309 │ 176 │
│ 10  │ gal_ab       │ 0.191816  │ 0.134573  │ 0.0572424  │ 0.0111975 │ 176 │
│ 11  │ gal_scale    │ 1.5971    │ 1.74828   │ -0.151179  │ 0.61436   │ 176 │
│ 12  │ gal_angle    │ 17.3836   │ 13.6815   │ 3.7021     │ 1.80406   │ 80  │
```
- 222.487737 seconds (8 threads)

joint infer @ .9 (540 / 585 sources converged)

```c++
│ Row │ field        │ primary   │ celeste   │ diff       │ diff_sd   │ N   │
├─────┼──────────────┼───────────┼───────────┼────────────┼───────────┼─────┤
│ 1   │ position     │ 0.357356  │ 0.238364  │ 0.118992   │ 0.0773965 │ 422 │
│ 2   │ missed_stars │ 0.0260664 │ 0.104265  │ -0.0781991 │ 0.0137841 │ 422 │
│ 3   │ missed_gals  │ 0.0545024 │ 0.0165877 │ 0.0379147  │ 0.010834  │ 422 │
│ 4   │ mag_r        │ 0.20834   │ 0.356943  │ -0.148603  │ 0.0199333 │ 422 │
│ 5   │ color_ug     │ 1.23383   │ 0.680855  │ 0.552975   │ 0.0547526 │ 375 │
│ 6   │ color_gr     │ 0.32552   │ 0.204252  │ 0.121268   │ 0.0163517 │ 419 │
│ 7   │ color_ri     │ 0.198864  │ 0.16092   │ 0.0379441  │ 0.0154802 │ 422 │
│ 8   │ color_iz     │ 0.290429  │ 0.13021   │ 0.160219   │ 0.0194342 │ 421 │
│ 9   │ gal_fracdev  │ 0.264358  │ 0.309233  │ -0.0448748 │ 0.0233503 │ 175 │
│ 10  │ gal_ab       │ 0.191482  │ 0.13334   │ 0.0581419  │ 0.0112111 │ 175 │
│ 11  │ gal_scale    │ 1.58769   │ 1.74125   │ -0.153563  │ 0.618143  │ 175 │
│ 12  │ gal_angle    │ 16.5969   │ 13.2057   │ 3.39122    │ 1.81539   │ 79  │
```
- 221.194958 seconds (8 threads)

### CODE REVIEW

**Comment by jeff-regier** [comment]
These results look great. How do the elbo values for the different configurations? (single vs joint@1/.95/.9)

**Comment by agnusmaximus** [comment]
Hmm not sure about the elbo values... what do you mean by this?

**Comment by agnusmaximus** [comment]
Also, yup I'll write a test case soon to make sure the gradient is near 0 after terminating

**Comment by jeff-regier** [comment]
The elbo is just another name for the objective function. I was curious about how different the objective function values are for the region of the sky that `validate_on_stripe82.jl` processes, for each of the 4 tests configurations you mention in this thread (single, joint@1.0, joint@0.95, joint@0.9).

Thanks for working on the gradient test. That test should pass when `termination_percent` is 1.0 presumably, but fail when `termination_precent` is 0.95.

**Pull request merged**
