### PR TITLE
Read catalog and WCS coordiantes.  Fix bug in PSF and compare to astrometry.net.

### PR DESCRIPTION
**Pull request by rgiordan**
Hey Jeff,

I'd like to merge this with master and get your sign-off before diving into moving the rest of Celeste over to world coordinates.

Ryan

### CODE REVIEW

**Comment by jeff-regier** [comment]
Looks good, though the unit tests don't pass on Travis. The error message is 

```
ERROR: `read_header` has no method matching read_header(::ImageHDU, ::Type{ASCIIString})
 in fetch_image at /home/travis/.julia/v0.3/Celeste/src/SDSS.jl:25
```

**Comment by rgiordan** [comment]
Hmm, I made a change to FITSIO.jl to implement that function.  It's been
merged, but maybe Travis hasn't picked it up yet.

**Comment by rgiordan** [comment]
Indeed, the Travis CI is using FITSIO.jl 0.7.0, and my system describes FITSIO.jl as 0.7.0+.  The tests pass on my machine.

Do you know how to correctly specify this in the REQUIRE file?  The julia docs for REQUIRE only describe pre-releases, like 0.8-.  I'm not sure what exactly 0.7.0+ means.

**Comment by jeff-regier** [comment]
I think the + means you've got a prereleased version of fitsio.jl checked
out. One way probably is to put the line Pkg.clone("http...") in the test
script. Another is to ask Kyle to push his changes by tagging it as a new
version. There's probably a better way still, but these are 2 ideas.

**Comment by rgiordan** [comment]
Kyle pushed a version and the tests now pass.

**Comment by jeff-regier** [comment]
Looks good. Is there a way to get test coverage of some of this new code?

**Comment by rgiordan** [comment]
Yes, but things are going to continue to change for a bit. Let me get
everything working on real images and then fill the test coverage back in
so as not to have to keep updating tests.

**Pull request merged**
