### PR TITLE
Fix galsim "unit test" and add some cases

### LINKED ISSUE #227: Unit tests based on synthetic data from GalSim
Another benefit of adding these tests: "All the test images in Synthetic.jl use either an identity WCS or a symmetric one. For testing purposes, we should replace them all with an actual asymmetric WCS.", from issue #90 , which this one subsumes.

### PR DESCRIPTION
**Pull request by gostevehoward**
Sadly this unit test was implemented in a completely broken way so it wasn't really checking
parameter values. This fixes that. i've also added a few additional cases and commented out the two
that are currently broken due to issue #482.

Closes #227.

### CODE REVIEW

**Comment by jeff-regier** [comment]
```
  assertion failed: |row[1,:ground_truth] - row[1,result_column]| <= 0.1
```

Does this finish #227 once it's merged?

**Comment by gostevehoward** [comment]
Yes, I was thinking this would close #227 and we'll update the test as we
find which additions would be useful.

That's odd that Travis failed since the test passes on my machine, both on
the branch as I pushed it and after rebasing the branch to upstream master.
Is there some source of nondeterminism, or maybe a difference in the
version of the Optim library or some other library...? Do you know of a
good way to debug travis failures? I'm not very familiar with the system.

**Comment by gostevehoward** [comment]
Whoops, it's because I had a different FITS file. Will fix.

**Comment by gostevehoward** [comment]
This reminds me, we really ought to explicitly version that GalSim FITS
file. Whether it's a timestamp or a git commit id or just a number, we
ought to put a version identifier in the FITS file name and explicitly
update it where it's referenced in the source when we make changes to the
file contents (changing test cases etc).

**Comment by gostevehoward** [comment]
Does this look familiar? (
https://travis-ci.org/jeff-regier/Celeste.jl/jobs/185321947)


Running test_derivatives.jl

Running ELBO derivative tests.

	FAILED: test_derivatives.jl

ERROR: LoadError: LoadError: StackOverflowError:

 in broadcast(::Base.#*, ::Float64,
::StaticArrays.SMatrix{2,2,Float64,4}) at
/home/travis/.julia/v0.6/StaticArrays/src/arraymath.jl:43 (repeats
80000 times)

while loading /home/travis/.julia/v0.6/Celeste/test/test_derivatives.jl,
in expression starting on line 1194

while loading /home/travis/.julia/v0.6/Celeste/test/runtests.jl, in
expression starting on line 69


On Wed, Dec 21, 2016 at 9:53 AM Steve Howard <dev@gostevehoward.com> wrote:

This reminds me, we really ought to explicitly version that GalSim FITS
file. Whether it's a timestamp or a git commit id or just a number, we
ought to put a version identifier in the FITS file name and explicitly
update it where it's referenced in the source when we make changes to the
file contents (changing test cases etc).

On Wed, Dec 21, 2016 at 9:48 AM Steve Howard <dev@gostevehoward.com> wrote:

Whoops, it's because I had a different FITS file. Will fix.

On Wed, Dec 21, 2016 at 9:44 AM Steve Howard <dev@gostevehoward.com> wrote:

Yes, I was thinking this would close #227 and we'll update the test as we
find which additions would be useful.

That's odd that Travis failed since the test passes on my machine, both on
the branch as I pushed it and after rebasing the branch to upstream master.
Is there some source of nondeterminism, or maybe a difference in the
version of the Optim library or some other library...? Do you know of a
good way to debug travis failures? I'm not very familiar with the system.

On Wed, Dec 21, 2016 at 9:34 AM Jeffrey Regier <notifications@github.com>
wrote:

  assertion failed: |row[1,:ground_truth] - row[1,result_column]| <= 0.1

Does this finish #227 <https://github.com/jeff-regier/Celeste.jl/issues/227>
once it's merged?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jeff-regier/Celeste.jl/pull/488#issuecomment-268587107>,
or mute the thread

**Comment by jeff-regier** [comment]
I haven't seen that error, but it looks like an upstream problem. I think it's good enough that the 0.5 tests are passing.

**Pull request merged**
