### PR TITLE
Don't initialize target sources based on SDSS (except for position)

### PR DESCRIPTION
**Pull request by jeff-regier**
This PR changes the way variational parameters are initialized, for all 4 combinations of mog/fft and single/joint. Target light source are no longer initialized based on the existing SDSS catalog, except for position. They're set to default values that seem to work well for optimization, e.g. a small galaxy radius. This change prepares us for initializing without an existing catalog. But the main reason for it is to get a better handle on whether joint inference and the fft PSF are working: we don't want single infer and the MOG to get "credit" if they get something right just because they get stuck in a shallow local optimum near primary's output.

### 1. Mixture-of-Gaussians PSF, single infer
For MOG PSF + single infer, on stripe 82, the scores are almost the same with initialization not based on primary. Only the number of missed stars is worse. 

```
│ Row │ field        │ primary   │ celeste   │ diff       │ diff_sd    │ N   │
├─────┼──────────────┼───────────┼───────────┼────────────┼────────────┼─────┤
│ 1   │ position     │ 0.243098  │ 0.235333  │ 0.00776518 │ 0.00717292 │ 417 │
│ 2   │ missed_stars │ 0.0263789 │ 0.100719  │ -0.0743405 │ 0.0139415  │ 417 │
│ 3   │ missed_gals  │ 0.0455635 │ 0.0215827 │ 0.0239808  │ 0.0094178  │ 417 │
│ 4   │ mag_r        │ 0.189753  │ 0.20523   │ -0.0154771 │ 0.0153515  │ 416 │
│ 5   │ color_ug     │ 1.25994   │ 0.687467  │ 0.572471   │ 0.0576229  │ 370 │
│ 6   │ color_gr     │ 0.30301   │ 0.190706  │ 0.112304   │ 0.0156293  │ 413 │
│ 7   │ color_ri     │ 0.18629   │ 0.14413   │ 0.0421602  │ 0.0154608  │ 416 │
│ 8   │ color_iz     │ 0.285698  │ 0.131208  │ 0.154489   │ 0.0205949  │ 417 │
│ 9   │ gal_fracdev  │ 0.260406  │ 0.199853  │ 0.0605529  │ 0.0223028  │ 173 │
│ 10  │ gal_ab       │ 0.189946  │ 0.141856  │ 0.0480895  │ 0.0112343  │ 173 │
│ 11  │ gal_scale    │ 1.54675   │ 0.587238  │ 0.959514   │ 0.850129   │ 173 │
│ 12  │ gal_angle    │ 17.6112   │ 12.7619   │ 4.84937    │ 1.76077    │ 81  │
```

### 2. Mixture-of-Gaussians PSF, joint infer
MOG + joint infer gets essentially the same scores as MOG + single infer. That's good news. Until single infer beats primary substantially, I wouldn't really expect joint infer to outperform single infer.
```
│ Row │ field        │ primary   │ celeste   │ diff        │ diff_sd   │ N   │
├─────┼──────────────┼───────────┼───────────┼─────────────┼───────────┼─────┤
│ 1   │ position     │ 0.243098  │ 0.244122  │ -0.00102337 │ 0.0139471 │ 417 │
│ 2   │ missed_stars │ 0.0263789 │ 0.0983213 │ -0.0719424  │ 0.0137699 │ 417 │
│ 3   │ missed_gals  │ 0.0455635 │ 0.0215827 │ 0.0239808   │ 0.0094178 │ 417 │
│ 4   │ mag_r        │ 0.189753  │ 0.204945  │ -0.0151928  │ 0.0155958 │ 416 │
│ 5   │ color_ug     │ 1.25994   │ 0.685607  │ 0.574331    │ 0.0573376 │ 370 │
│ 6   │ color_gr     │ 0.30301   │ 0.193017  │ 0.109993    │ 0.0156854 │ 413 │
│ 7   │ color_ri     │ 0.18629   │ 0.141066  │ 0.0452237   │ 0.0154659 │ 416 │
│ 8   │ color_iz     │ 0.285698  │ 0.124966  │ 0.160732    │ 0.0199686 │ 417 │
│ 9   │ gal_fracdev  │ 0.260406  │ 0.204749  │ 0.0556566   │ 0.022389  │ 173 │
│ 10  │ gal_ab       │ 0.189946  │ 0.143833  │ 0.0461126   │ 0.0112096 │ 173 │
│ 11  │ gal_scale    │ 1.54675   │ 0.611111  │ 0.93564     │ 0.850138  │ 173 │
│ 12  │ gal_angle    │ 17.6112   │ 13.441    │ 4.17024     │ 1.82835   │ 81  │
```

### 3. FFT PSF, single infer
Signs of life from the FFT PSF. Whereas MOG + single infer misclassifies 10% of stars as galaxies, FFT + single infer misclassifies only 7% of stars as galaxies. That's what we'd want to see from the new PSF model: a misspecified PSF model won't fit stars well, so they're vulnerable to getting labeled as galaxies. 

Unfortunately the number of galaxies misclassified as stars increases, so it's not entirely clear whether the reduction of `missed_stars` is due to better fits, or due a different algorithm ending up at a different point on the same ROC curve, but I suspect it's the former. 

@rgiordan -- `mag_r` is off by a lot, compared to both primary and MOG. Maybe worth looking into?

```
│ Row │ field        │ primary   │ celeste   │ diff       │ diff_sd    │ N   │
├─────┼──────────────┼───────────┼───────────┼────────────┼────────────┼─────┤
│ 1   │ position     │ 0.243098  │ 0.268371  │ -0.0252727 │ 0.00902318 │ 417 │
│ 2   │ missed_stars │ 0.0263789 │ 0.0695444 │ -0.0431655 │ 0.0109604  │ 417 │
│ 3   │ missed_gals  │ 0.0455635 │ 0.0359712 │ 0.00959233 │ 0.0114188  │ 417 │
│ 4   │ mag_r        │ 0.189753  │ 0.308458  │ -0.118705  │ 0.0228481  │ 416 │
│ 5   │ color_ug     │ 1.25994   │ 0.719576  │ 0.540361   │ 0.0565404  │ 370 │
│ 6   │ color_gr     │ 0.30301   │ 0.215291  │ 0.0877188  │ 0.0172613  │ 413 │
│ 7   │ color_ri     │ 0.18629   │ 0.17835   │ 0.00793941 │ 0.0166771  │ 416 │
│ 8   │ color_iz     │ 0.285698  │ 0.160172  │ 0.125526   │ 0.0209171  │ 417 │
│ 9   │ gal_fracdev  │ 0.260406  │ 0.235728  │ 0.0246778  │ 0.0243053  │ 173 │
│ 10  │ gal_ab       │ 0.189946  │ 0.156961  │ 0.032985   │ 0.0115975  │ 173 │
│ 11  │ gal_scale    │ 1.54675   │ 0.632484  │ 0.914268   │ 0.849509   │ 173 │
│ 12  │ gal_angle    │ 17.6112   │ 13.272    │ 4.33923    │ 1.79721    │ 81  │
```

### 4. FFT PSF + Joint Infer
Initializing elbo args took 60 GB memory, so probably a bug there.
```
│ Row │ field        │ primary   │ celeste   │ diff       │ diff_sd   │ N   │
├─────┼──────────────┼───────────┼───────────┼────────────┼───────────┼─────┤
│ 1   │ position     │ 0.243098  │ 0.333939  │ -0.0908403 │ 0.0304764 │ 417 │
│ 2   │ missed_stars │ 0.0263789 │ 0.0719424 │ -0.0455635 │ 0.0111926 │ 417 │
│ 3   │ missed_gals  │ 0.0455635 │ 0.0407674 │ 0.00479616 │ 0.0114188 │ 417 │
│ 4   │ mag_r        │ 0.189753  │ 0.334224  │ -0.144471  │ 0.0285082 │ 416 │
│ 5   │ color_ug     │ 1.25994   │ 0.734911  │ 0.525027   │ 0.0572994 │ 370 │
│ 6   │ color_gr     │ 0.30301   │ 0.230272  │ 0.0727377  │ 0.0210699 │ 413 │
│ 7   │ color_ri     │ 0.18629   │ 0.204191  │ -0.0179014 │ 0.0252074 │ 416 │
│ 8   │ color_iz     │ 0.285698  │ 0.170183  │ 0.115515   │ 0.0231709 │ 417 │
│ 9   │ gal_fracdev  │ 0.260406  │ 0.214921  │ 0.0454843  │ 0.0239973 │ 173 │
│ 10  │ gal_ab       │ 0.189946  │ 0.155252  │ 0.0346933  │ 0.011639  │ 173 │
│ 11  │ gal_scale    │ 1.54675   │ 0.636098  │ 0.910654   │ 0.849731  │ 173 │
│ 12  │ gal_angle    │ 17.6112   │ 14.0442   │ 3.56699    │ 1.92718   │ 81  │
```

### CODE REVIEW

**Comment by jeff-regier** [comment]
@agnusmaximus   For your test on line 368 of test_joint_infer.jl (i.e. `@test score_multi > score_single`), you compare joint and single infer, but the values are almost exactly the same (on the master branch, before this PR, and with this PR). If the sources overlap, shouldn't joint do substantially better? (Are you accidentally initializing the sources to the ground truth, rather than perturbed values, or something?)

The changes in this PR seem to break the test occasionally, but only because `score_multi` and `score_single` are so similar. From master:
```
One node joint infer objective value: -16502.795298177654
Single iter objective value: -16502.795768391097
```

**Comment by agnusmaximus** [comment]
Hmm, yeah they are pretty close... weird. 

I'm not sure if I'm initializing the sources to the ground truth -- the joint infer initializes every source by calling init_source during preallocation. This isn't the same as initializing to ground truth is it?

Would overlapping to a very small degree be the cause for the tiny differences in objective value? If I optimize more sources (like 20), the differences in objective value are much greater (8-9 rather than < 1). 

For example, on the bounding box `box = BoundingBox(154.39, 164.41, 39.11, 39.13) ` with 20 sources I get
```c++
One node joint infer objective value: -81628.14388391141
One node joint infer 2 iter objective value: -81655.40940585428
Single iter objective value: -81637.42304209441
```

**Comment by agnusmaximus** [comment]
I recall that you mentioned that even though the sources are listed as overlapping in neighbor_maps, that they might not actually overlap or something. Maybe this is related to the issue.

To fix this, I'll make a pull request that runs the test on more overlapping sources (such as the 20 sources above).

**Comment by jeff-regier** [comment]
That seemed to work, thanks. Yeah calling `init_source(ce)` (now renamed to `catalog_init_source`)  initializes everything to their settings from the SDSS catalog, which isn't too far from the ground truth. That makes it harder for joint infer to show improvement over single infer, but evidently with 20 sources it's still possible.

**Comment by agnusmaximus** [comment]
Hmm, I didn't know that. Is there a way to initialize the source to random values rather than close to the ground truth?

Edit: Nvm I can just randomly initialize the parameter values manually
Edit2: Ah, I see generic_init_source which I'm trying out right now

**Comment by jeff-regier** [comment]
Perfect, that's it. The values of `generic_init_source` should be way off, so single infer should do worse that when the neighbors are initialized well.

**Comment by agnusmaximus** [comment]
With generic_init_source instead of catalog_init_source:

```c++
One node joint infer objective value: -81626.92584034224
One node joint infer 2 iter objective value: -179429.25416665032
Single iter objective value: -81636.44982854737
```

Edit: Ah wait, so that's with joint_infer using only generic_init source. Single iter is still using catalog_init_souce. Will update when both have been switched to use generic_init_source.

With generic_init_source used for both single and joint infer:
```c++
One node joint infer objective value: -81626.92561329095
One node joint infer 2 iter objective value: -179429.31285384388
Single iter objective value: -1.3171102049515678e6
```

**Comment by agnusmaximus** [comment]
When generic_init_source is used for both single and joint infer, on the 4 sources where there wasn't much difference between the two methods:

```c++
One node joint infer objective value: -16502.79037381859
One node joint infer 2 iter objective value: -16702.926456277335
Single iter objective value: -54756.790745877035
```

**Comment by jeff-regier** [comment]
Nice results!

**Pull request merged**
