### PR TITLE
No type call

### PR DESCRIPTION
**Pull request by jeff-regier**
@kpamnany -- There's some chance this PR is a workaround for the segfault from SDSSIO.jl:315.

### CODE REVIEW

**Comment by kpamnany** [comment]
LGTM. Merge it, so I can pull it into `src_div_par`?

**Comment by kpamnany** [comment]
Hmm. I rebased on master and see:

```
$ bin/celeste.jl infer-box 200.0 200.05 38.0 38.05 $SCRATCH
ERROR: LoadError: LoadError: LoadError: LoadError: UndefVarError: RawPSF not defined
 in include_from_node1(::String) at ./loading.jl:488 (repeats 3 times)
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:415
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /global/homes/k/kpamnany/.local/share/julia/packages-cori/v0.5/Celeste/src/model/psf_model.jl, in expression starting on line 480
while loading /global/homes/k/kpamnany/.local/share/julia/packages-cori/v0.5/Celeste/src/Model.jl, in expression starting on line 48
while loading /global/homes/k/kpamnany/.local/share/julia/packages-cori/v0.5/Celeste/src/Celeste.jl, in expression starting on line 8
while loading /global/u1/k/kpamnany/Celeste.jl/bin/celeste.jl, in expression starting on line 5
```

There isn't even a line 480 in `psf_model.jl`, but any idea what's wrong?

**Comment by kpamnany** [comment]
I moved `image_model.jl` which defines `RawPSF` above `psf_model.jl` in `Model.jl`. Unfortunately, there's a mutual dependency -- now it complains that `PsfComponent` is not defined in `image_model.jl`. I'm not sure how this is working in master?

**Comment by kpamnany** [comment]
No wait, I see that `RawPSF` has been moved to `psf_model.jl` in master. Why did this not propagate to my branch?? I'll fix it.

**Comment by jeff-regier** [comment]
Oh good....I wasn't able to recreate the issue over here.

**Comment by kpamnany** [comment]
_sigh_ No fix, exact same segfault.

```
[247]<6> fetching RCF 373 (4382, 1, 65)
[96]<3> fetching RCF 160 (3893, 4, 242)
[96]<7> fetching RCF 148 (3893, 3, 243)

signal (11): Segmentation fault
while loading /global/homes/k/kpamnany/Celeste.jl/bin/celeste.jl, in expression starting on line 72
unknown function (ip: 0x2aace3f01fff)
fit_object_psfs! at /global/homes/k/kpamnany/.local/share/julia/packages-cori/v0.5/Celeste/src/Infer.jl:189
unknown function (ip: 0x2aace3e0da76)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
infer_source at /global/homes/k/kpamnany/.local/share/julia/packages-cori/v0.5/Celeste/src/Infer.jl:104
unknown function (ip: 0x2aacdb83caad)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
optimize_source at /global/homes/k/kpamnany/.local/share/julia/packages-cori/v0.5/Celeste/src/source_division_inference.jl:465
unknown function (ip: 0x2aacdb82a1f4)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
process_tasks at /global/homes/k/kpamnany/.local/share/julia/packages-cori/v0.5/Celeste/src/source_division_inference.jl:560
```

**Comment by jeff-regier** [comment]
Damn.

Will you push your latest changes to src_div_par, so the line numbers match?

These errors look slightly different...they don't mention a particular line
in the psf fitting code.

How quickly were you able to get this error? Can you send Jameson
instructions for recreating it?

**Comment by kpamnany** [comment]
This is the error that happens when it crashes at start. The error when it crashes at the end is a bit different. It happens consistently at 64 node runs, but I don't think Jameson can get on Cori right now and getting 64 nodes on Edison ... forget it. I'll try more print statements...

**Comment by jeff-regier** [comment]
How about trying a run with the `@inbounds` macros removed? From within the `src` directory, you can get rid of all of them just by running

```
sed -i 's/@inbounds //' *.jl */*.jl
```

**Comment by andreasnoack** [comment]
You can also just run Julia with `--check-bounds=true`. That disables the effect of `@inbounds`.

**Comment by jeff-regier** [comment]
Good to know!

**Pull request merged**
