### PR TITLE
Remove the mean / variance parameterization from the free transform

### PR DESCRIPTION
**Pull request by rgiordan**
This change actually makes newton's method work great.

### CODE REVIEW

**Comment by rgiordan** [comment]
Both these are failing due to a missing REQUIRE in GaussianMixtures.  I've submitted a pull request to them.

**Comment by jeff-regier** [comment]
Looks like some tests are failing

**Comment by rgiordan** [comment]
See my other message.  It's a bug in distributions.jl.  I've submitted a
pull request to them.

**Comment by rgiordan** [comment]
He's pushed the change but Travis isn't picking it up.  I'm making lots of little changes, and though I'd like to package them into nice reviewable chunks for you, it's going to be clunky if we can't merge things while we wait on other packages to fix stuff.

Maybe you can just merge these and accept a broken build in exchange for more reviewable pulls.  There are more on the way.

**Pull request merged**
