### PR TITLE
Convergence problems

### LINKED ISSUE #130: Make sure all the necessary sources are included
@kbarbary , the way `celeste.jl` divides up the celestial objects isn't correct -- you can't partition the catalog entries by slicing the array.  If two objects are in the same tile, then you need to make sure both the objects are in the model params object.

One correct way to do it is something like the block of code in `limit_to_object_data` where I populate the `relevant_sources` vector.

### PR DESCRIPTION
**Pull request by rgiordan**
@kbarbary , @jeff-regier PTAL.  This fixes https://github.com/jeff-regier/Celeste.jl/issues/130 (and opens https://github.com/jeff-regier/Celeste.jl/issues/143)

### CODE REVIEW

**Comment by rgiordan** [comment]
NB: 0.4 tests pass, 0.5 tests fail (as usual)

**Comment by kbarbary** [comment]
Looks good to me.

Given that we're moving towards just single objects in #123, I think it's fine to get rid of all the `part` stuff and `cat_entries[minidx:maxidx]` if you want to go ahead and do that here.

**Comment by rgiordan** [comment]
If it's ok with you, I'll let you and Rollin do this since the two of you
are deciding together on the API.

**Comment by kbarbary** [comment]
Makes sense.

**Pull request merged**
