### PR TITLE
Temporarily allow failures on nightly

### PR DESCRIPTION
**Pull request by andreasnoack**

### CODE REVIEW

**Comment by jeff-regier** [comment]
@rgiordan  OK if we increase the threshold here, or is this something to be concerned about?
```
FAILED: test_eda.jl
ERROR: LoadError: LoadError: assertion failed: |maximum(abs((fft_img_12 - fft_img_1) - fft_img_2)) - 0.0| <= 1.0e-15
  maximum(abs((fft_img_12 - fft_img_1) - fft_img_2)) = 1.7763568394002505e-15
```

**Comment by jeff-regier** [comment]
Errors from FileIO too...

```
ERROR: LoadError: LoadError: UndefVarError: readbytes not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:539
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:539
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /home/travis/.julia/v0.6/FileIO/src/query.jl, in expression starting on line 311
while loading /home/travis/.julia/v0.6/FileIO/src/FileIO.jl, in expression starting on line 32
ERROR: LoadError: Failed to precompile FileIO to /home/travis/.julia/lib/v0.6/FileIO.ji.
```

**Comment by rgiordan** [comment]
@jeff-regier , it'd be fine to increase that to something bigger but still small, like ```1e-12```.

**Comment by andreasnoack** [comment]
I've adjusted the two tolerances in `test_eda` to `1e-12`. @rgiordan The macro `@test_approx_eq_eps` is now deprecated in favor of using `@test isapprox(a,b)` with the optional keyword arguments `atol` and `rtol` for absolute and relative tolerance.

**Comment by jeff-regier** [comment]
Thanks a lot Andreas! Nice to have useful tests again :-)

**Pull request merged**
