### PR TITLE
Multinode functionality

### PR DESCRIPTION
**Pull request by kpamnany**
Also changed parts of `ParallelRun.jl`; @jeff-regier: please review.

### CODE REVIEW

**Comment by Keno** [comment]
Do we really want to comming cfg/sky_boxes?

**Comment by kpamnany** [comment]
It's the current best-known sorting of boxes in decreasing order of difficulty. We need to use that for the hero run.

**Comment by jeff-regier** [comment]
@kpamnany Looks fine except that you accidentally included `sky_boxes` in the commit!

**Comment by kpamnany** [comment]
I did that intentionally @jeff-regier; I consider the sorting to be useful/important information about SDSS. I can remove it though, if you prefer?

**Comment by jeff-regier** [comment]
Yeah, please exclude it. We've been keeping data files on remote servers, and having Celeste fetch them as needed, so that's one option.

**Comment by Keno** [comment]
You'll need to squash this. Other it'll take up space in the repo

**Pull request merged**
